name: 'Flutter action'
description: 'Setup your runner with Flutter environment'
author: 'Alif Rachmawadi'
branding:
  icon: 'maximize'
  color: 'blue'
inputs:
  flutter-version:
    description: 'The Flutter version to make available on the path'
    required: false
    default: 'any'
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
  cache:
    description: 'Cache the Flutter SDK'
    required: false
  cache-key:
    description: 'Identifier for the Flutter SDK cache'
    required: false
    default: 'flutter'
  cache-path:
    description: 'Flutter SDK cache path'
    required: false
    default: ${{ runner.tool_cache }}/flutter
  architecture:
    description: 'The architecture of Flutter SDK executable (x64 or arm64)'
    required: false
    default: ${{ runner.arch }}
  false-positive-cache:
    description: 'Ensure up-to-date Flutter SDK but, Occuring False Positive Cache-hit'
    required: false
runs:
  using: 'composite'
  steps:
    - if: ${{ inputs.cache == 'true' && inputs.false-positive-cache == 'true' }}
      shell: bash
      run: |
        os_name=$(echo ${{ runner.os }} | awk '{print tolower($0)}')
        manifest_base_url="https://storage.googleapis.com/flutter_infra_release/releases"
        manifest_url="$manifest_base_url/releases_$os_name.json"
        releases_manifest=$(curl --silent --connect-timeout 15 --retry 5 $manifest_url)
        if [[ $os_name == 'windows' ]]; then
          echo "manifest_hash=$(echo -n $releases_manifest | sha256sum | cut -c -7)" >>$GITHUB_ENV
        else
          echo "manifest_hash=$(echo -n $releases_manifest | shasum -a 256 | cut -c -7)" >>$GITHUB_ENV
        fi
    - if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}-${{ runner.os }}-${{ inputs.architecture }}-${{ inputs.channel }}-${{ inputs.flutter-version }}-${{ env.manifest_hash }}
    - run: $GITHUB_ACTION_PATH/setup.sh -c "${{ inputs.cache-path }}" ${{ inputs.channel }} ${{ inputs.flutter-version }} ${{ inputs.architecture }}
      shell: bash
