name: 'Flutter action'
description: 'Setup your runner with Flutter environment'
author: 'Alif Rachmawadi'
inputs:
  flutter-version:
    description: 'The Flutter version to make available on the path'
    required: false
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
  flutter-versio-frigidus:
    description: 'Use Flutter version located in file created by flutter_versio_frigidus?'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'maximize'
  color: 'blue'
